name: Publish to maven central

on:
  push:
    branches:
      - main
      - projectSetup # development 2025-11
    tags:
      - '**'
  workflow_dispatch:

permissions:
  actions: write
  contents: read
  pull-requests: write

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}-${{ github.event_name }}"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'corretto'
          check-latest: true
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - id: istagbuild
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "tagbuild=true" >> "$GITHUB_OUTPUT"
          else
            echo "tagbuild=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Decode secretKeyRingFile
        id: secring
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'secring.gpg'
          encodedString: ${{ secrets.KOPPOR_SIGNING_SECRETKEYRINGFILE_BASE64 }}
      - name: store secrets
        run: |
          cat >> gradle.properties <<EOF
          signing.keyId=${{ secrets.KOPPOR_SIGNING_KEYID }}
          signing.password=${{ secrets.KOPPOR_SIGNING_PASSWORD }}
          signing.secretKeyRingFile=${{ steps.secring.outputs.filePath }}
          mavenCentralUsername=${{ secrets.KOPPOR_MAVENCENTRALUSERNAME }}
          mavenCentralPassword=${{ secrets.KOPPOR_MAVENCENTRALPASSWORD }}
          EOF
          grep secretKeyRingFile gradle.properties
          file ${{ steps.secring.outputs.filePath }}
          md5sum ${{ steps.secring.outputs.filePath }}
      - name: publishAllPublicationsToMavenCentralRepository
        run: |
          ./gradlew -Ptagbuild="$tagbuild" publishAllPublicationsToMavenCentralRepository
